import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import{ClerkProvider}from '@clerk/nextjs'

// Rename to distinguish each font use
const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const openSansMono = Open_Sans({
  variable: "--font-open-sans-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Discord-clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${openSans.variable} ${openSansMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
