import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";

// Load fonts
const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const openSansMono = Open_Sans({
  variable: "--font-open-sans-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Discord-clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={cn(
            "bg-white text-black dark:bg-[#2e2f30] dark:text-white", // ✅ softer dark background
            openSans.variable,
            openSansMono.variable,
            "antialiased"
          )}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
            storageKey="discord-theme"
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
